### ISSUE TITLE
[PATCH] fix spelling error in manpage

### ISSUE THREAD

**Issue by lucaskanashiro** [rjbs/Pod-Elemental#5]
In Debian we are currently applying the following patch to
Pod-Elemental.
We thought you might be interested in it too.

```
Description: fix spelling error in manpage
Author: Lucas Kanashiro <kanashiro.duarte@gmail.com>
Last-Update: 2015-08-16
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libpod-elemental-perl.git/plain/debian/patches/fix_spelling_error_in_manpage.patch

Thanks for considering,
  Lucas Kanashiro,
  Debian Perl Group

**Comment by rjbs** [comment]
Thank you for being in touch.

**I believe this change is a mistake.**

My documentation reads:

> It works by being told what elements may be made
> into containers and what subsequent elements they should allow 
> to be stuffed into them.

That is:  It is told what elements should be allowed to be stuffed into what other elements.  There is no elided noun.

Please stop applying the patch in Debian.

**Comment by rjbs** [comment]
@lucaskanashiro As near as I can tell, this patch is still being applied, despite being wrong.

**Comment by rjbs** [comment]
Now fixed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949849
